apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: skill-repeater-ingress
  namespace: skill-repeater
spec:
  entryPoints:
    - websecure
  routes:
    # Skill Repeater Service
    - match: Host(`api.posadskiy.com`) && PathPrefix(`/skill-repeater`)
      kind: Rule
      services:
        - name: skill-repeater-service
          port: 8210
      middlewares:
        - name: cors-middleware
        - name: strip-prefix-skill-repeater
        - name: rate-limit-middleware
      priority: 10
    
    # Skill Repeater Frontend
    - match: Host(`repeaty.posadskiy.com`)
      kind: Rule
      services:
        - name: skill-repeater-front
          port: 3000
      middlewares:
        - name: cors-middleware
        - name: rate-limit-middleware
      priority: 10
  tls:
    certResolver: letsencrypt

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors-middleware
  namespace: skill-repeater
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    accessControlAllowHeaders:
      - DNT
      - User-Agent
      - X-Requested-With
      - If-Modified-Since
      - Cache-Control
      - Content-Type
      - Range
      - Authorization
    accessControlExposeHeaders:
      - Content-Length
      - Content-Range
    accessControlAllowCredentials: true
    accessControlAllowOriginList:
      - https://repeaty.posadskiy.com
    accessControlMaxAge: 1728000
    customRequestHeaders:
      X-Forwarded-Proto: https
      X-Real-IP: ""
      X-Forwarded-For: ""
      X-Forwarded-Host: ""

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit-middleware
  namespace: skill-repeater
spec:
  rateLimit:
    average: 100
    period: 1s
    burst: 50

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-skill-repeater
  namespace: skill-repeater
spec:
  stripPrefix:
    prefixes:
      - /skill-repeater

