apiVersion: v1
kind: Secret
metadata:
  name: skill-repeater-secrets
  namespace: skill-repeater
type: Opaque
stringData:
  DATASOURCE_PASSWORD: "${SKILL_REPEATER_DATABASE_PASSWORD_PROD}"
  JWT_GENERATOR_SIGNATURE_SECRET: "${JWT_GENERATOR_SIGNATURE_SECRET}"
  GITHUB_TOKEN: "${GITHUB_TOKEN}" 
